
name: Special Build Backend

on:
  push

jobs:
  push_to_registry:
    name: Build & Push to Registries
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.0
        with:
          # Use a role instead of including credentials in secrets, but still hide that role name to be gated by GH environments.
          role-to-assume: ${{ secrets.ECR_REPO_ROLE }}
          role-duration-seconds: 7200 # 2 hours
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Determine Tags BackEnd
        id: meta_backend
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/strelka-backend
            sublimesec/strelka-backend
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build BackEnd
        uses: docker/build-push-action@v2
        with:
          file: build/python/backend/Dockerfile
          context: .
          load: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}

      - name: Push BackEnd
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push --all-tags sublimesec/strelka-backend
